Add ansible as a package dependency
When using the V2 agent, the plugins (file, email, etc..) are loaded
via ansible.executor. If the package is not present we get this
error :

ImportError: No module named ansible.executor

By default the dci-agent package doesn't have a requirement on
ansible.

Change-Id: Ia8dc6f52edaddc9da91db686776e80553eb5fffb